on: 
  push:
  workflow_dispatch:
    inputs:
      environmentselector:
        description: 'Environment selector'     
        required: false
        default: 'default'

jobs:
  setup:
    name: Choose Secrets Environment Job
    runs-on: windows-latest
    steps:
      - id: setup
        name: Setup Environment Setp
        run: |
          $envSelector = "${{ github.event.inputs.environmentselector }}"
          Write-Host "Environment Selector: $envSelector Branch ${{ github.ref }}"
          if ($envSelector -eq '' -or $envSelector -eq 'default') {            
            if ('${{ github.ref }}' -eq 'refs/heads/main') { 
              echo "::set-output name=build_env::PROD_"
            } else {
              echo "::set-output name=build_env::DEV_"
            }
          } else {
            echo "::set-output name=build_env::$envSelector"
          }
    outputs:
      build_env: ${{ steps.setup.outputs.build_env }}

  build_deploy:
    name: Build and Deploy
    needs: setup
    runs-on: ubuntu-latest
    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
           - 10000:10000
           - 10001:10001

      azure-cosmos-emulator:
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
        ports:
           - 8081:8081
           - 8900:8900
           - 8901:8901
           - 8902:8902
           - 10250:10250
           - 10251:10251
           - 10252:10252
           - 10253:10253
           - 10254:10254
           - 10255:10255
           - 10256:1025
           - 10350:10350
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - id: integrationtest
        name: Integration Tests
        run: |
            dotnet test ~/HotelReservationTests/HotelReservationTests.csproj --logger junit;LogFilePath=${{ env.RUNNER_TEMP }}\TestResults\unittests.xml

      - name: Publish test results
        if: ${{ always() }}
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        with:
          files: ${{ env.RUNNER_TEMP }}/TestResults/*.xml